<a href="https://colab.research.google.com/github/Majela12/apuntesIA/blob/main/Apuntes_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Vairables en python
Las variables categoricas o text se guardan inicialmente en tipo object
las variables numericas se guardan en tipo int o float (8,16,32,64)

#cargar los datos
##cargar un dataframe
###crear dataset usando numpy

*tabulacion

In [ ]:
import pandas as pd
import numpy as np

# Crear un dataset simulado
np.random.seed(42)
data = {
    "Estudiante": [f"E{i}" for i in range(1, 21)],
    "Edad": np.random.randint(18, 25, size=20),
    "Género": np.random.choice(["Femenino", "Masculino"], size=20),
    "Nota_Matemáticas": np.random.normal(70, 10, size=20).round(1),
    "Nota_Ciencias": np.random.normal(75, 12, size=20).round(1),
    "Nota_Inglés": np.random.normal(65, 15, size=20).round(1),
}

In [6]:
!python -v

import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'posix' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
# installing zipimport hook
import 'time' # <class '_frozen_importlib.BuiltinImporter'>
import 'zipimport' # <class '_frozen_importlib.FrozenImporter'>
# installed zipimport hook
# /usr/lib/python3.11/encodings/__pycache__/__init__.cpython-311.pyc matches /usr/lib/python3.11/encodings/__init__.py
# code object from '/usr/lib/python3.11/encodings/__pycache__/__init__.cpython-311.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <class '_frozen_impor

In [7]:
!pip list

Package                            Version
---------------------------------- -------------------
absl-py                            1.4.0
accelerate                         1.3.0
aiohappyeyeballs                   2.4.6
aiohttp                            3.11.12
aiosignal                          1.3.2
alabaster                          1.0.0
albucore                           0.0.23
albumentations                     2.0.4
ale-py                             0.10.1
altair                             5.5.0
annotated-types                    0.7.0
anyio                              3.7.1
argon2-cffi                        23.1.0
argon2-cffi-bindings               21.2.0
array_record                       0.6.0
arviz                              0.20.0
astropy                            7.0.1
astropy-iers-data                  0.2025.2.10.0.33.26
astunparse                         1.6.3
atpublic                           4.1.0
attrs                              25.1.0
audioread          

In [10]:
# prompt: crear dos listas de numpy una con 10 nombres inventados y 10 edades tambien inventadas inventadas

import numpy as np

# Crear una lista de 10 nombres inventados
nombres = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy'])

# Crear una lista de 10 edades inventadas
edades = np.array([25, 32, 19, 45, 28, 31, 22, 29, 38, 27])
print(nombres)
print(edades)


['Alice' 'Bob' 'Charlie' 'David' 'Eve' 'Frank' 'Grace' 'Heidi' 'Ivan'
 'Judy']
[25 32 19 45 28 31 22 29 38 27]


In [11]:
type(nombres)

numpy.ndarray

In [12]:
nombres.shape

(10,)

In [13]:
# prompt: colocar un arreglo de (5,2) donde en la primera columna coloque la primera es el valor unitario y la segunda es la cantidad

import numpy as np

# Crear un arreglo de (5, 2)
data = np.array([
    [10, 2],  # Valor unitario: 10, Cantidad: 2
    [5, 5],   # Valor unitario: 5, Cantidad: 5
    [20, 1],  # Valor unitario: 20, Cantidad: 1
    [15, 3],  # Valor unitario: 15, Cantidad: 3
    [8, 4]    # Valor unitario: 8, Cantidad: 4
])

data


array([[10,  2],
       [ 5,  5],
       [20,  1],
       [15,  3],
       [ 8,  4]])

In [14]:
# prompt: Multiplicar las dos columnas del arreglo data y agregarlo para quedar en la forma (5,3)

# Multiplicar las dos columnas del arreglo data
multiplicacion = data[:, 0] * data[:, 1]

# Crear un nuevo arreglo con la forma (5, 3)
nuevo_data = np.zeros((5, 3))

# Copiar los datos originales a las primeras dos columnas del nuevo arreglo
nuevo_data[:, :2] = data

# Agregar el resultado de la multiplicación a la tercera columna
nuevo_data[:, 2] = multiplicacion

nuevo_data


array([[10.,  2., 20.],
       [ 5.,  5., 25.],
       [20.,  1., 20.],
       [15.,  3., 45.],
       [ 8.,  4., 32.]])

In [15]:
# prompt: calcular el promedio de la columna 0 de data

# Assuming 'data' is the NumPy array defined in the previous code.
# If 'data' is a pandas DataFrame, use data.iloc[:, 0].mean() instead.

promedio_columna_0 = np.mean(data[:, 0])
print(f"El promedio de la columna 0 es: {promedio_columna_0}")


El promedio de la columna 0 es: 11.6


In [24]:
promedio_column1=np.min(data[:,1])
promedio_column1

1

In [26]:
identidad=np.eye(5,5)
identidad


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

el profesor gritó cuando dijo que hacer operaciones con arreglo era usar numpy

In [27]:
# prompt: Creame un dataframe con el nombre, el cargo, el salario y la antiguedad en años, poner 20 filas con datos sintéticos

import pandas as pd
import numpy as np

# Crear datos sintéticos
np.random.seed(42)  # Para reproducibilidad (datos aleatorios, punto de arranque)

num_rows = 20
nombres = ['Nombre_' + str(i) for i in range(1, num_rows + 1)]
cargos = np.random.choice(['Analista', 'Ingeniero', 'Gerente', 'Desarrollador'], size=num_rows)
salarios = np.random.randint(30000, 100000, size=num_rows)
antiguedades = np.random.randint(1, 10, size=num_rows)

# Crear el DataFrame
df = pd.DataFrame({
    'Nombre': nombres,
    'Cargo': cargos,
    'Salario': salarios,
    'Antiguedad': antiguedades
})

df


Nombre          Cargo  Salario  Antiguedad
0    Nombre_1        Gerente    97221           9
1    Nombre_2  Desarrollador    94820           3
2    Nombre_3       Analista    30769           5
3    Nombre_4        Gerente    89735           3
4    Nombre_5        Gerente    92955           7
5    Nombre_6  Desarrollador    94925           5
6    Nombre_7       Analista    97969           9
7    Nombre_8       Analista    35311           7
8    Nombre_9        Gerente    83707           2
9   Nombre_10      Ingeniero    58693           4
10  Nombre_11        Gerente    55658           9
11  Nombre_12        Gerente    48431           2
12  Nombre_13        Gerente    32747           9
13  Nombre_14        Gerente    89150           5
14  Nombre_15  Desarrollador    95725           2
15  Nombre_16       Analista    65773           4
16  Nombre_17  Desarrollador    97435           7
17  Nombre_18  Desarrollador    86886           8
18  Nombre_19  Desarrollador    96803           3
19  Nombre_20        Gerente    61551           1

In [33]:
df.Salario.mean()

75313.2

In [34]:
df.Salario.max()

97969

In [28]:
type(df)

pandas.core.frame.DataFrame

In [35]:
df.Antiguedad.var()

7.43157894736842

In [36]:
df[df.Salario>90000]

Nombre          Cargo  Salario  Antiguedad
0    Nombre_1        Gerente    97221           9
1    Nombre_2  Desarrollador    94820           3
4    Nombre_5        Gerente    92955           7
5    Nombre_6  Desarrollador    94925           5
6    Nombre_7       Analista    97969           9
14  Nombre_15  Desarrollador    95725           2
16  Nombre_17  Desarrollador    97435           7
18  Nombre_19  Desarrollador    96803           3

In [38]:
df.Cargo.unique()

array(['Gerente', 'Desarrollador', 'Analista', 'Ingeniero'], dtype=object)

In [41]:
cantidad=df.Cargo.value_counts()
cantidad

Cargo
Gerente          9
Desarrollador    6
Analista         4
Ingeniero        1
Name: count, dtype: int64